# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.formGroupBox.setGeometry(QtCore.QRect(30, 30, 271, 151))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_10 = QtWidgets.QLabel(self.formGroupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.formGroupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.formGroupBox1.setGeometry(QtCore.QRect(150, 190, 151, 121))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.formGroupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.formGroupBox2.setGeometry(QtCore.QRect(30, 190, 101, 121))
        self.formGroupBox2.setObjectName("formGroupBox2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formGroupBox2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.formGroupBox2)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formGroupBox2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_8 = QtWidgets.QLabel(self.formGroupBox2)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formGroupBox2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formGroupBox2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formGroupBox2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(410, 40, 361, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mplvl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mplvl.setContentsMargins(0, 0, 0, 0)
        self.mplvl.setObjectName("mplvl")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.mplvl.addWidget(self.widget)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(470, 330, 251, 191))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.formGroupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.formGroupBox3.setGeometry(QtCore.QRect(140, 350, 121, 161))
        self.formGroupBox3.setAlignment(QtCore.Qt.AlignCenter)
        self.formGroupBox3.setObjectName("formGroupBox3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formGroupBox3)
        self.formLayout_4.setContentsMargins(15, 10, -1, -1)
        self.formLayout_4.setHorizontalSpacing(25)
        self.formLayout_4.setVerticalSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label0 = QtWidgets.QLabel(self.formGroupBox3)
        self.label0.setObjectName("label0")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label0)
        self.label1 = QtWidgets.QLabel(self.formGroupBox3)
        self.label1.setObjectName("label1")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label1)
        self.label2 = QtWidgets.QLabel(self.formGroupBox3)
        self.label2.setObjectName("label2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label2)
        self.label3 = QtWidgets.QLabel(self.formGroupBox3)
        self.label3.setObjectName("label3")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label3)
        self.label4 = QtWidgets.QLabel(self.formGroupBox3)
        self.label4.setObjectName("label4")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label4)
        self.label5 = QtWidgets.QLabel(self.formGroupBox3)
        self.label5.setObjectName("label5")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label5)
        self.label6 = QtWidgets.QLabel(self.formGroupBox3)
        self.label6.setObjectName("label6")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.formGroupBox.setTitle(_translate("MainWindow", "Параметры модели"))
        self.label.setText(_translate("MainWindow", "Количество требований"))
        self.label_2.setText(_translate("MainWindow", "Количество устройств"))
        self.label_3.setText(_translate("MainWindow", "A"))
        self.label_4.setText(_translate("MainWindow", "S"))
        self.label_10.setText(_translate("MainWindow", "Емкость очереди"))
        self.formGroupBox1.setTitle(_translate("MainWindow", "Параметры генераторов"))
        self.label_5.setText(_translate("MainWindow", "SEED A"))
        self.label_6.setText(_translate("MainWindow", "SEED S"))
        self.formGroupBox2.setTitle(_translate("MainWindow", "Приоритеты"))
        self.label_7.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "2"))
        self.label_9.setText(_translate("MainWindow", "3"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.verticalGroupBox_2.setTitle(_translate("MainWindow", "Графики"))
        self.pushButton_1.setText(_translate("MainWindow", "Коэффициент использования системы"))
        self.pushButton_2.setText(_translate("MainWindow", "Число требований в очереди"))
        self.pushButton_3.setText(_translate("MainWindow", "Число требований в системе"))
        self.pushButton_4.setText(_translate("MainWindow", "Среднее число требований в очереди"))
        self.pushButton_5.setText(_translate("MainWindow", "Среднее число требований в системе"))
        self.formGroupBox3.setTitle(_translate("MainWindow", "Характеристики"))
        self.label_11.setText(_translate("MainWindow", "p"))
        self.label_12.setText(_translate("MainWindow", "Tq"))
        self.label_13.setText(_translate("MainWindow", "Ts"))
        self.label_14.setText(_translate("MainWindow", "Nq"))
        self.label_15.setText(_translate("MainWindow", "Ns"))
        self.label_16.setText(_translate("MainWindow", "Ca"))
        self.label_17.setText(_translate("MainWindow", "Cr"))
        self.label0.setText(_translate("MainWindow", "-"))
        self.label1.setText(_translate("MainWindow", "-"))
        self.label2.setText(_translate("MainWindow", "-"))
        self.label3.setText(_translate("MainWindow", "-"))
        self.label4.setText(_translate("MainWindow", "-"))
        self.label5.setText(_translate("MainWindow", "-"))
        self.label6.setText(_translate("MainWindow", "-"))

